// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEVkFoRbUJ-vIoOeL2dU03z95f9f1f2lc',
    appId: '1:621075193625:web:66fc030caab4ba6d3faf88',
    messagingSenderId: '621075193625',
    projectId: 'project1-eef5f',
    authDomain: 'project1-eef5f.firebaseapp.com',
    storageBucket: 'project1-eef5f.appspot.com',
    measurementId: 'G-TGQPRKW3NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGaNKWc9nmeCTX5n1tNshx2fWntG2ViI',
    appId: '1:621075193625:android:7a33c907e3a9ccc43faf88',
    messagingSenderId: '621075193625',
    projectId: 'project1-eef5f',
    storageBucket: 'project1-eef5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNUUB1IHgP7Q8UxfYk5rKCqRMa9Ehwmk',
    appId: '1:621075193625:ios:084f055ab9e4d6133faf88',
    messagingSenderId: '621075193625',
    projectId: 'project1-eef5f',
    storageBucket: 'project1-eef5f.appspot.com',
    iosClientId: '621075193625-6lbpbkqp4liud3a093l30gdnffimu26r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluterBlocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPNUUB1IHgP7Q8UxfYk5rKCqRMa9Ehwmk',
    appId: '1:621075193625:ios:084f055ab9e4d6133faf88',
    messagingSenderId: '621075193625',
    projectId: 'project1-eef5f',
    storageBucket: 'project1-eef5f.appspot.com',
    iosClientId: '621075193625-6lbpbkqp4liud3a093l30gdnffimu26r.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluterBlocApp',
  );
}
